const VELLURE_PAGAMENTOS_KEY='vellure_pagamentos';
const VELLURE_PAG_CONFIG_KEY='vellure_pag_config';
function obterConfigPagamento(){return JSON.parse(localStorage.getItem(VELLURE_PAG_CONFIG_KEY)||'null')||{chavePix:'11966818500',tipoChave:'Telefone',beneficiario:'Vellure Studio',cidade:'São Paulo',sinalPercentual:30,cartaoHabilitado:true,recorrenciaHabilitada:true}}
function salvarConfigPagamento(v){localStorage.setItem(VELLURE_PAG_CONFIG_KEY,JSON.stringify(v))}
function obterPagamentos(){return JSON.parse(localStorage.getItem(VELLURE_PAGAMENTOS_KEY)||'[]')}
function salvarPagamentos(v){localStorage.setItem(VELLURE_PAGAMENTOS_KEY,JSON.stringify(v))}
function valorNumero(v){return Number(String(v||'').replace(/[^0-9,.-]/g,'').replace('.','').replace(',','.'))||0}
function dinheiro(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function gerarIdPagamento(){return Date.now()+Math.floor(Math.random()*999)}
function registrarPagamento(dados){const arr=obterPagamentos();const registro={id:gerarIdPagamento(),criadoEm:new Date().toISOString(),status:'Aguardando',...dados};arr.unshift(registro);salvarPagamentos(arr);return registro}
function atualizarPagamento(id,alteracoes){const arr=obterPagamentos();const i=arr.findIndex(x=>x.id===id);if(i<0)return;arr[i]={...arr[i],...alteracoes,atualizadoEm:new Date().toISOString()};salvarPagamentos(arr);renderFinanceiro();renderHistoricoCliente()}
function excluirPagamento(id){if(!confirm('Excluir este registro financeiro?'))return;salvarPagamentos(obterPagamentos().filter(x=>x.id!==id));renderFinanceiro()}
function servicoSelecionadoPagamento(){const select=document.getElementById('servico');if(!select||!select.value)return null;const valorSelecionado=select.value;const opcao=select.options[select.selectedIndex];const nomeOpcao=opcao?.dataset?.nome||opcao?.textContent?.split(' (R$')[0].replace(/^.*? — /,'').trim()||'';const servicos=window.obterServicos?obterServicos():(window.VELLURE_SERVICOS||[]);const servico=servicos.find(x=>String(x.id)===String(valorSelecionado))||servicos.find(x=>x.nome===nomeOpcao);if(servico)return servico;return {id:valorSelecionado,nome:nomeOpcao,preco:opcao?.dataset?.preco||''}}
function precoServicoSelecionado(){return valorNumero(servicoSelecionadoPagamento()?.preco)}
function atualizarResumoPagamento(){const box=document.getElementById('resumoPagamento');if(!box)return;const servico=servicoSelecionadoPagamento();const valor=valorNumero(servico?.preco);const cfg=obterConfigPagamento();const tipo=document.querySelector('input[name="tipoPagamento"]:checked')?.value||'sinal';const pagar=tipo==='total'?valor:valor*(cfg.sinalPercentual/100);document.getElementById('valorProcedimento').textContent=servico&&valor?`${servico.nome} • ${dinheiro(valor)}`:'Selecione o serviço';document.getElementById('valorPagar').textContent=valor?dinheiro(pagar):'—';document.getElementById('textoCondicao').textContent=tipo==='total'?'Pagamento integral do procedimento':`Sinal de ${cfg.sinalPercentual}% para reserva`;const metodo=document.querySelector('input[name="metodoPagamento"]:checked')?.value||'PIX';document.getElementById('detalhePix').hidden=metodo!=='PIX';document.getElementById('detalheCartao').hidden=metodo!=='Cartão';document.getElementById('chavePixExibida').textContent=cfg.chavePix}
function lerComprovante(input,cb){const f=input.files?.[0];if(!f)return cb(null);if(f.size>1500000){alert('Use um comprovante de até 1,5 MB.');input.value='';return cb(null)}const r=new FileReader();r.onload=()=>cb({nome:f.name,tipo:f.type,dados:r.result});r.readAsDataURL(f)}
function prepararPagamentoAgendamento(){const form=document.getElementById('formReserva');if(!form)return;['servico','tipoPagamento','metodoPagamento'].forEach(nome=>{document.querySelectorAll(`#${nome},input[name="${nome}"]`).forEach(el=>el.addEventListener('change',atualizarResumoPagamento))});atualizarResumoPagamento()}
function criarRegistroAgendamento(){const valor=precoServicoSelecionado();const cfg=obterConfigPagamento();const tipo=document.querySelector('input[name="tipoPagamento"]:checked')?.value||'sinal';const metodo=document.querySelector('input[name="metodoPagamento"]:checked')?.value||'PIX';const valorCobrado=tipo==='total'?valor:valor*(cfg.sinalPercentual/100);return new Promise(resolve=>lerComprovante(document.getElementById('comprovante'),comp=>{resolve(registrarPagamento({cliente:document.getElementById('nome').value.trim(),telefone:document.getElementById('telefone').value.trim(),servico:document.getElementById('servico').value,dataAtendimento:document.getElementById('data').value,horario:document.getElementById('horario').value,metodo,tipo:tipo==='total'?'Pagamento total':'Sinal',valorTotal:valor,valorPago:valorCobrado,recorrente:false,comprovante:comp,notas:document.getElementById('notasPagamento')?.value.trim()||'',origem:'Agendamento pelo site'}))}))}
function badgeStatus(s){return `<span class="status ${s==='Cancelado'?'off':''}">${s}</span>`}
function renderFinanceiro(){const tbody=document.getElementById('tabelaPagamentos');if(!tbody)return;const arr=obterPagamentos();const filtro=(document.getElementById('filtroPagamento')?.value||'').toLowerCase();const lista=arr.filter(p=>!filtro||[p.cliente,p.servico,p.metodo,p.status,p.tipo].join(' ').toLowerCase().includes(filtro));tbody.innerHTML=lista.length?lista.map(p=>`<tr><td><b>${p.cliente||'Cliente'}</b><small>${p.telefone||''}</small></td><td>${p.servico||p.plano||'—'}<small>${p.tipo||''}</small></td><td>${p.metodo||'—'}</td><td>${dinheiro(p.valorPago)}<small>de ${dinheiro(p.valorTotal)}</small></td><td>${badgeStatus(p.status)}</td><td>${p.comprovante?`<button class="mini-action" onclick="abrirComprovante(${p.id})">Ver arquivo</button>`:'—'}</td><td class="table-actions"><button onclick="editarPagamento(${p.id})">Editar</button><button onclick="marcarPago(${p.id})">Confirmar</button><button class="danger" onclick="excluirPagamento(${p.id})">Excluir</button></td></tr>`).join(''):`<tr><td colspan="7">Nenhum pagamento registrado.</td></tr>`;const pagos=arr.filter(p=>p.status==='Pago');const soma=m=>pagos.filter(p=>p.metodo===m).reduce((a,p)=>a+Number(p.valorPago||0),0);document.getElementById('statPix').textContent=dinheiro(soma('PIX'));document.getElementById('statCartao').textContent=dinheiro(soma('Cartão'));document.getElementById('statPendente').textContent=dinheiro(arr.filter(p=>p.status==='Aguardando').reduce((a,p)=>a+Number(p.valorPago||0),0));document.getElementById('statTotal').textContent=dinheiro(pagos.reduce((a,p)=>a+Number(p.valorPago||0),0))}
function marcarPago(id){atualizarPagamento(id,{status:'Pago',pagoEm:new Date().toISOString()})}
function editarPagamento(id){const p=obterPagamentos().find(x=>x.id===id);if(!p)return;document.getElementById('pagamentoId').value=id;document.getElementById('pagCliente').value=p.cliente||'';document.getElementById('pagServico').value=p.servico||p.plano||'';document.getElementById('pagValorTotal').value=p.valorTotal||'';document.getElementById('pagValorPago').value=p.valorPago||'';document.getElementById('pagMetodo').value=p.metodo||'PIX';document.getElementById('pagTipo').value=p.tipo||'Pagamento total';document.getElementById('pagStatus').value=p.status||'Aguardando';document.getElementById('pagNotas').value=p.notas||'';document.getElementById('pagRecorrente').checked=!!p.recorrente;document.getElementById('editorPagamento').classList.add('active')}
function novoPagamento(){document.getElementById('formPagamento').reset();document.getElementById('pagamentoId').value='';document.getElementById('editorPagamento').classList.add('active')}
function fecharPagamento(){document.getElementById('editorPagamento').classList.remove('active')}
function salvarFormularioPagamento(e){e.preventDefault();const id=Number(document.getElementById('pagamentoId').value);const dados={cliente:document.getElementById('pagCliente').value.trim(),servico:document.getElementById('pagServico').value.trim(),valorTotal:Number(document.getElementById('pagValorTotal').value),valorPago:Number(document.getElementById('pagValorPago').value),metodo:document.getElementById('pagMetodo').value,tipo:document.getElementById('pagTipo').value,status:document.getElementById('pagStatus').value,notas:document.getElementById('pagNotas').value.trim(),recorrente:document.getElementById('pagRecorrente').checked};const finalizar=comp=>{if(id)atualizarPagamento(id,{...dados,...(comp?{comprovante:comp}:{})});else registrarPagamento({...dados,comprovante:comp,origem:'Lançamento manual'});fecharPagamento();renderFinanceiro()};lerComprovante(document.getElementById('pagComprovante'),finalizar)}
function abrirComprovante(id){const p=obterPagamentos().find(x=>x.id===id);if(!p?.comprovante?.dados)return alert('Comprovante não encontrado.');const w=window.open();if(p.comprovante.tipo?.includes('pdf'))w.location=p.comprovante.dados;else w.document.write(`<title>Comprovante</title><img src="${p.comprovante.dados}" style="max-width:100%;display:block;margin:auto">`)}
function abrirConfigPagamento(){const c=obterConfigPagamento();document.getElementById('cfgChavePix').value=c.chavePix;document.getElementById('cfgTipoChave').value=c.tipoChave;document.getElementById('cfgBeneficiario').value=c.beneficiario;document.getElementById('cfgCidade').value=c.cidade;document.getElementById('cfgSinal').value=c.sinalPercentual;document.getElementById('cfgCartao').checked=c.cartaoHabilitado;document.getElementById('cfgRecorrencia').checked=c.recorrenciaHabilitada;document.getElementById('configPagamento').classList.add('active')}
function salvarConfiguracaoPagamento(e){e.preventDefault();salvarConfigPagamento({chavePix:document.getElementById('cfgChavePix').value.trim(),tipoChave:document.getElementById('cfgTipoChave').value,beneficiario:document.getElementById('cfgBeneficiario').value.trim(),cidade:document.getElementById('cfgCidade').value.trim(),sinalPercentual:Number(document.getElementById('cfgSinal').value)||30,cartaoHabilitado:document.getElementById('cfgCartao').checked,recorrenciaHabilitada:document.getElementById('cfgRecorrencia').checked});document.getElementById('configPagamento').classList.remove('active');atualizarResumoPagamento();alert('Configurações salvas.')}
function renderHistoricoCliente(){const box=document.getElementById('historicoPagamentosCliente');if(!box)return;const arr=obterPagamentos().slice(0,5);box.innerHTML=arr.length?arr.map(p=>`<div class="payment-history-item"><div><b>${p.servico||p.plano}</b><span>${p.tipo} • ${p.metodo}</span></div><div><strong>${dinheiro(p.valorPago)}</strong>${badgeStatus(p.status)}</div></div>`).join(''):'<p>Nenhum pagamento registrado.</p>'}
document.addEventListener('DOMContentLoaded',()=>{prepararPagamentoAgendamento();renderFinanceiro();renderHistoricoCliente();document.getElementById('formPagamento')?.addEventListener('submit',salvarFormularioPagamento);document.getElementById('formConfigPagamento')?.addEventListener('submit',salvarConfiguracaoPagamento);document.getElementById('filtroPagamento')?.addEventListener('input',renderFinanceiro)});
